### PR TITLE
fix: e.isLid is not a function

### PR DESCRIPTION
**Pull request by jrrcdev**
This commit fix the e.isLid is not a function issue https://github.com/orkestral/venom/issues/1792 https://github.com/orkestral/venom/issues/1790

### CODE REVIEW

**Comment by xzvcit** [comment]
checkNumberStatus got empty object

**Comment by benoli** [comment]
Thanks mate!

**Comment by eldevanjr** [comment]
@jrrcdev , I've got the same error, how can i use the fix on my node project that uses venom as npm dependency? if i use as file dependency  and run : ` node app.js`
  throw this error:
```

venom-bot/dist/controllers/welcome.js:9
const latest_version_1 = require("latest-version");
                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module venom-bot/node_modules/latest-version/index.js from venom-bot/dist/controllers/welcome.js not supported.
Instead change the require of index.js in venom-bot/dist/controllers/welcome.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (venom-bot/dist/controllers/welcome.js:9:26)
    at Object.<anonymous> (venom-bot/dist/controllers/initializer.js:67:19)
    at Object.<anonymous> (venom-bot/dist/index.js:85:21)
    at Object.<anonymous> (/home/eldevan/workspace/infokaw-sendmsg/app.js:3:15) {
  code: 'ERR_REQUIRE_ESM'
}

any idea, how can i use the patch that I merge on my fork?
```

**Comment by joaocib** [comment]
> @jrrcdev , I've got the same error, how can i use the fix on my node project that uses venom as npm dependency? if i use as file dependency and run : ` node app.js` throw this error:
> 
> ```
> 
> venom-bot/dist/controllers/welcome.js:9
> const latest_version_1 = require("latest-version");
>                          ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module venom-bot/node_modules/latest-version/index.js from venom-bot/dist/controllers/welcome.js not supported.
> Instead change the require of index.js in venom-bot/dist/controllers/welcome.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (venom-bot/dist/controllers/welcome.js:9:26)
>     at Object.<anonymous> (venom-bot/dist/controllers/initializer.js:67:19)
>     at Object.<anonymous> (venom-bot/dist/index.js:85:21)
>     at Object.<anonymous> (/home/eldevan/workspace/infokaw-sendmsg/app.js:3:15) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> any idea, how can i use the patch that I merge on my fork?
> ```

- download or clone the repository (the current version with src folder) and open it using vscode.
- apply the solution by changing it manually or pull a branch on github.
-  use npm run build in this new project (if you face webpack issues, install it globally). 
- this process will create a new dist folder (with the pull request solution).
- go to your main project, find venom-bot, update the dist folder with this new one

**Comment by iShi0n** [comment]
> > @jrrcdev , I've got the same error, how can i use the fix on my node project that uses venom as npm dependency? if i use as file dependency and run : ` node app.js` throw this error:
> > ```
> > 
> > venom-bot/dist/controllers/welcome.js:9
> > const latest_version_1 = require("latest-version");
> >                          ^
> > 
> > Error [ERR_REQUIRE_ESM]: require() of ES Module venom-bot/node_modules/latest-version/index.js from venom-bot/dist/controllers/welcome.js not supported.
> > Instead change the require of index.js in venom-bot/dist/controllers/welcome.js to a dynamic import() which is available in all CommonJS modules.
> >     at Object.<anonymous> (venom-bot/dist/controllers/welcome.js:9:26)
> >     at Object.<anonymous> (venom-bot/dist/controllers/initializer.js:67:19)
> >     at Object.<anonymous> (venom-bot/dist/index.js:85:21)
> >     at Object.<anonymous> (/home/eldevan/workspace/infokaw-sendmsg/app.js:3:15) {
> >   code: 'ERR_REQUIRE_ESM'
> > }
> > 
> > any idea, how can i use the patch that I merge on my fork?
> > ```
> 
> * download or clone the repository (the current version with src folder) and open it using vscode.
> * apply the solution by changing it manually or pull a branch on github.
> * use npm run build in this new project (if you face webpack issues, install it globally).
> * this process will create a new dist folder (with the pull request solution).
> * go to your main project, find venom-bot, update the dist folder with this new one

thx :)

**Comment by marlos7** [comment]
It looks like the developer who was maintaining this project created a project of his own! I used it here, it's getting really good!
https://github.com/jonalan7/Hydra-bot

**Comment by renandecarlo** [comment]
> > @jrrcdev , I've got the same error, how can i use the fix on my node project that uses venom as npm dependency? if i use as file dependency and run : ` node app.js` throw this error:
> > ```
> > 
> > venom-bot/dist/controllers/welcome.js:9
> > const latest_version_1 = require("latest-version");
> >                          ^
> > 
> > Error [ERR_REQUIRE_ESM]: require() of ES Module venom-bot/node_modules/latest-version/index.js from venom-bot/dist/controllers/welcome.js not supported.
> > Instead change the require of index.js in venom-bot/dist/controllers/welcome.js to a dynamic import() which is available in all CommonJS modules.
> >     at Object.<anonymous> (venom-bot/dist/controllers/welcome.js:9:26)
> >     at Object.<anonymous> (venom-bot/dist/controllers/initializer.js:67:19)
> >     at Object.<anonymous> (venom-bot/dist/index.js:85:21)
> >     at Object.<anonymous> (/home/eldevan/workspace/infokaw-sendmsg/app.js:3:15) {
> >   code: 'ERR_REQUIRE_ESM'
> > }
> > 
> > any idea, how can i use the patch that I merge on my fork?
> > ```
> 
> * download or clone the repository (the current version with src folder) and open it using vscode.
> * apply the solution by changing it manually or pull a branch on github.
> * use npm run build in this new project (if you face webpack issues, install it globally).
> * this process will create a new dist folder (with the pull request solution).
> * go to your main project, find venom-bot, update the dist folder with this new one

You can also use my repo, which contains these fixes already.
`npm i github:renandecarlo/venom`

**Comment by nicoroms** [comment]
> @jrrcdev , I've got the same error, how can i use the fix on my node project that uses venom as npm dependency? if i use as file dependency and run : ` node app.js` throw this error:
> 
> ```
> 
> venom-bot/dist/controllers/welcome.js:9
> const latest_version_1 = require("latest-version");
>                          ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module venom-bot/node_modules/latest-version/index.js from venom-bot/dist/controllers/welcome.js not supported.
> Instead change the require of index.js in venom-bot/dist/controllers/welcome.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (venom-bot/dist/controllers/welcome.js:9:26)
>     at Object.<anonymous> (venom-bot/dist/controllers/initializer.js:67:19)
>     at Object.<anonymous> (venom-bot/dist/index.js:85:21)
>     at Object.<anonymous> (/home/eldevan/workspace/infokaw-sendmsg/app.js:3:15) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> any idea, how can i use the patch that I merge on my fork?
> ```

you can force the version of a dependency of your package with "overrides". This is an example of my package.json.

`{
  "name": "-",
  "type": "module",
  "version": "1.0.0",
  "main": "main.js",
  "scripts": {
    "prd": "node ./src/main.js"
  },
  "dependencies": {
    "venom-bot": "github:orkestral/venom#pull/1794/head"
  },
  "overrides": {
    "venom-bot": {
      "latest-version": "5.1.0"
    }
  }
}
`

**Comment by lavahasif** [comment]
image
change the current version `latest-version : ^'7.0.0' to ^5.0.0 `then build

**Pull request merged**
