### PR TITLE
Provides a documentation for venom

### PR DESCRIPTION
**Pull request by tadeubarbosa**
Some classes and functions need to be documented, but there's the most used.

### CODE REVIEW

**Comment by tadeubarbosa** [comment]
Can someone help me to fix that lint error? I can't find it.

**Comment by edgardmessias** [comment]
Of course, you must rebase your commits e fix the commit description.

How to write commits: https://www.conventionalcommits.org/pt-br/v1.0.0-beta.4/

How to rebase commits messages: https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/changing-a-commit-message

**Comment by joaosouz4dev** [comment]
@tadeubarbosa in next time try to use https://www.conventionalcommits.org/pt-br/v1.0.0-beta.4/

**Comment by joaosouz4dev** [comment]
@tadeubarbosa  THANK U!

**Pull request merged**
